server:
  port: 8001
  servlet:
    context-path: /member

spring:
  datasource:
    url: jdbc:mysql://43.138.26.5:3306/train_member?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: train_member
    password: Sss030323
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

logging:
  level:
    com.sss.train.member.mapper: trace
